### ISSUE TITLE
Error converting to String

### ISSUE THREAD

**Issue by paul** [wasmerio/ruby-ext-wasm#78]
Seems like this project is probably dead, but I'm reporting this anyways. It doesn't seem like it works in the latest versions.

### Describe the bug

I can't run the examples, I get an error:

> Error converting to String (TypeError)

### Steps to reproduce

```
$ ruby examples/appendices/simple.rb
examples/appendices/simple.rb:8: warning: undefining the allocator of T_DATA class Wasmer::Store
examples/appendices/simple.rb:11:in `new': Error converting to String (TypeError)

module_ = Wasmer::Module.new store, IO.read(file, mode: "rb")
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from examples/appendices/simple.rb:11:in `<main>'
```

### Additional context

```
$ ruby -v
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]

$ rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15)
```

**Comment by rajesh1211** [comment]
Any fix for this? Facing exact same issue
